---
title: "DSR versus NRR Survival Analysis"
author:
  - Kevin E. See:
      email: Kevin.See@dfw.wa.gov
      institute: [wdfw]
      correspondence: false
  - Michael W. Ackerman:
      email: mike.ackerman@mthoodenvironmental.com
      institute: [mhe_mccall]
      correspondence: true
  - Nick Porter:
      email: Nicholas.Porter@merck.com
      institute: [biomark]
      correspondence: true
  - Mike Hall:
      email: Mike.Hall1@merck.com
      institute: [biomark]
      correspondence: false
  - Richie Carmichael:
      email: Richard.Carmichael@merck.com
      institute: [biomark]
      correspondence: false
institute:
  - wdfw: Washington Department of Fish and Wildife, Fish Program, Science Division, 1111 Washington Street NE, Olympia, Washington, 98501, USA
  - mhe_mccall: Mount Hood Environmental, PO Box 4282, McCall, Idaho, 83638, USA
  - biomark: Biomark, Inc., 705 South 8th Street, Boise, Idaho, 83702, USA
date: "`r format(Sys.time(), '%d %B, %Y')`" 
output:
  bookdown::html_document2:
    theme: yeti
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    number_sections: yes
    pandoc_args:
    - --lua-filter=../templates/scholarly-metadata.lua
    - --lua-filter=../templates/author-info-blocks.lua
    - --lua-filter=../templates/pagebreak.lua  
csl: "../templates/american-fisheries-society.csl"
bibliography:
  - AckermanLibrary.bib
---

```{r setup, echo = FALSE, message = F, warning = F}
library(here)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = here("analysis/figures/"),
  dpi = 300
)
```

```{r}
# load packages
library(tidyverse)
library(janitor)
library(lubridate)
library(PITcleanr)
library(magrittr)
library(rstan)

theme_set(theme_bw())
```

Text
  
