---
title: "Habitat Use versus Availability by Juvenile Chinook Salmon in Winter Months, Lemhi River"
author:
  - Kevin E. See:
      email: Kevin.See@dfw.wa.gov
      institute: [wdfw]
      correspondence: false
  - Michael W. Ackerman:
      email: mike.ackerman@mthoodenvironmental.com
      institute: [mhe_mccall]
      correspondence: true 
  - Nick Porter:
      email: Nicholas.Porter@merck.com
      institute: [biomark]
      correspondence: true
  - Tulley Mackey:
      email: tulley.mackey@mthoodenvironmental.com
      institute: [mhe_salmon]
      correspondence: false
  - Mike Hall:
      email: Mike.Hall1@merck.com
      institute: [biomark]
      correspondence: false
  - Richie Carmichael:
      email: Richard.Carmichael@merck.com
      institute: [biomark]
      correspondence: false
institute:
  - wdfw: Washington Department of Fish and Wildife, Fish Program, Science Division, 1111 Washington Street NE, Olympia, Washington, 98501, USA
  - mhe_mccall: Mount Hood Environmental, PO Box 4282, McCall, Idaho, 83638, USA
  - biomark: Biomark, Inc., 705 South 8th Street, Boise, Idaho, 83702, USA
  - mhe_salmon: Mount Hood Environmental, 1009 South Daisy Street, Salmon, Idaho, 83467, USA
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    theme: yeti
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    number_sections: yes
    pandoc_args:
    - --lua-filter=../templates/scholarly-metadata.lua
    - --lua-filter=../templates/author-info-blocks.lua
    - --lua-filter=../templates/pagebreak.lua  
csl: "../templates/american-fisheries-society.csl"
bibliography:
  - AckermanLibrary.bib
always_allow_html: yes
---

```{r setup, echo = FALSE, message = F, warning = F}
library(here)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = here("analysis/figures//"),
  dpi = 300
)

```

```{r packages}
# load packages
library(tidyverse)
library(here)
library(magrittr)
library(janitor)

theme_set(theme_bw())

```

```{r load-data}
load(here("analysis/data/derived_data/habitat_available.rda"))
load(here("analysis/data/derived_data/habitat_use.rda"))

```

```{r clean-data}
xs_all = xs_use %>%
  mutate(source = "use") %>%
  bind_rows(xs_avail %>%
              mutate(source = "avail")) %>%
  clean_names() %>%
  # improve some column names
  rename(release_loc = location,
         release_date = release,
         xs_name = name,
         stream_name = stream_nam,
         sin_cat = category,
         frazil_ice = frazel_ice) %>%
  # correct the code for small side channels
  mutate(channel_unit_type = recode(channel_unit_type,
                                    `SC` = "SSC")) %>%
  # round distance to cover to nearest 0.1m and rename
  mutate(distance_to_cover = round(distance_to_cover_round_to_nearest_0_1m, 1)) %>%
  select(-distance_to_cover_round_to_nearest_0_1m) %>%
  # fix some names within dominant substrate and reorder levels
  mutate(dominant_substrate_1mx1m = fct_recode(dominant_substrate_1mx1m,
                                               Boulder = "boulder",
                                               Cobble = "cobble",
                                               Fines = "silt_fines",
                                               Sand = "sand",
                                               Gravel = "gravel"),
         dominant_substrate_1mx1m = fct_relevel(dominant_substrate_1mx1m,
                                                "Gravel",
                                                after = 2),
         dominant_substrate_1mx1m = fct_relevel(dominant_substrate_1mx1m,
                                                "Sand",
                                                after = 3)) %>%
  # add a variable of wehtere there's any cover present within 1.5m
  mutate(has_cover = if_else(dominant_cover_type_1_5m_radius %in% c("No Cover", "Unknown") | is.na(dominant_cover_type_1_5m_radius),
                             "No", "Yes"))
  
  

```
